services:
  mongodb:
    image: mongo:latest
    env_file: .env
    container_name: mongodb
    hostname: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - ./data/lsj.json:/docker-entrypoint-initdb.d/lsj.json
      - ./data/bdb.json:/docker-entrypoint-initdb.d/bdb.json
    command: >
      bash -c "
        mongod --fork --logpath /var/log/mongodb.log --bind_ip_all &&
        sleep 3 &&
        mongoimport --db DICS --collection entries --file /docker-entrypoint-initdb.d/lsj.json --jsonArray &&
        mongoimport --db DICS --collection entries --file /docker-entrypoint-initdb.d/bdb.json --jsonArray &&
        mongod --shutdown &&
        mongod --bind_ip_all
      "
    networks:
      - internal
    
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dic-api
    hostname: dic-api
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: ["uvicorn", "api.app:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    networks:
      - internal

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: dic-frontend
    ports: 
      - "5174:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - internal
  
networks:
  internal:
    driver: bridge