FROM python:3.9-slim

RUN python3 -m pip install --upgrade pip --

WORKDIR /app

COPY ./backend/requirements.txt /app/requirements.txt

RUN python3 -m pip install -r /app/requirements.txt

COPY ./backend/api /app/api

# This is the port that FastAPI will be listening on inside the container
EXPOSE 8000

# Healthcheck to monitor the application
HEALTHCHECK CMD ["curl", "--fail", "http://localhost:8000", "||", "exit 1"]

CMD ["uvicorn", "api.app:app", "--host", "0.0.0.0", "--port", "8000"]